#!/bin/bash

Execute_Input_CHECK "Do You want to install pptpd-1.3.4 ? (Y/N)"
if [ "$IS_EXECUTE" = "ture" ];then
    unset IP_TABLES_CHECK IP_TABLES_CHECK_FLAG PPP_CHECK
    while :
    do
        PPP_CHECK=$(rpm -qa |grep ppp)
        if [ -z "$PPP_CHECK" ] ;then
            yum -y install ppp
            PPP_CHECK_FLAG="ture"
        else
            break 
        fi
        IP_TABLES_CHECK=$(lsmod|grep ip_tables)
        if [ -z "$IP_TABLES_CHECK" ];then 
            modprobe ip_tables  
            IP_TABLES_CHECK_FLAG="ture"
        else
            break
        fi
    done
    if [ "$IP_TABLES_CHECK_FLAG" = "ture" ];then
        Color_Msg red "\nmodprobe iptables error,install pptpd fail"
    else
        echo "INSTALL_PPTPD"
    fi

    Color_Msg cyan 'Install pptpd ...'
    cd ${STORE_DIR}
    unset SRC SRC_DIR FILE_EXT SUM COMPO_CONFIG
    COMPO_CONFIG="./configure --prefix=/usr/local/pptpd"
    parser_file ${PPTPD_SRC}
    rm -rf  "${SRC_DIR}"
    get_file
    unpack || Install_Failed "$SRC"
    Color_Msg cyan 'Installing ...'
    cd $SRC_DIR 
    echo  $COMPO_CONFIG || Install_Failed "$SRC"
    eval $COMPO_CONFIG || Install_Failed "$SRC"
    Color_Msg green "Making $SRC ..."
    make || Install_Failed "$SRC"
    Color_Msg green "Installing $SRC ..."
    make install || Install_Failed "$SRC"
    echo $SRC_DIR
    cp -f ${SELF_PATH}/conf/pptpd/options.pptpd /etc/ppp/options.pptpd
    cp -f ${SELF_PATH}/conf/pptpd/pptpd.conf /etc/pptpd.conf 
    cp -f ${SELF_PATH}/conf/pptpd/chap-secrets /etc/ppp/chap-secrets
    if [ -n "$(grep " *net.ipv4.ip_forward" /etc/sysctl.conf)" ] ;then
        sed -i "/net.ipv4.ip_forward/s/0/1/" /etc/sysctl.conf 
    else
        echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
    fi
    sysctl -p
    iptables -t nat -A POSTROUTING -o eth0 -s 192.168.10.0/24 -j MASQUERADE
    /usr/local/pptpd/sbin/pptpd -c /etc/pptpd.conf
    Color_Msg green "The default VPN user is admin , password is admin"
    Color_Msg green "If you want to change it ,please edit /etc/ppp/chap-secrets"
fi
